// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace LessIsMoore.UITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// OpenHomePage - Use 'OpenHomePageParams' to pass parameters into this method.
        /// </summary>
        public void OpenHomePage()
        {
            #region Variable Declarations
            BrowserWindow uIBlankPageInternetExpWindow = this.UIBlankPageInternetExpWindow;
            #endregion

            // Go to web page 'http://localhost:5000/exAm?sf=8d679ae7-e939-474c-a3ff-8501ee636b12'
            uIBlankPageInternetExpWindow.NavigateToUrl(new System.Uri(this.OpenHomePageParams.UIBlankPageInternetExpWindowUrl));
        }
        
        /// <summary>
        /// TakeExam - Use 'TakeExamParams' to pass parameters into this method.
        /// </summary>
        public void TakeExam()
        {
            #region Variable Declarations
            HtmlEdit uITxtNameEdit = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UITxtNameEdit;
            HtmlEdit uITxtEmailEdit = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UITxtEmailEdit;
            HtmlLabel uIEnableAlwaysOnLabel = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIEnableAlwaysOnLabel;
            HtmlDocument uIHomePageAzureExamDocument = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument;
            HtmlLabel uIDeploymentslotsLabel = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIDeploymentslotsLabel;
            HtmlRadioButton uIEnableWebSocketsRadioButton = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIEnableWebSocketsRadioButton;
            HtmlLabel uIAPIManagementLabel = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIAPIManagementLabel;
            HtmlRadioButton uICreateanewdeploymentRadioButton = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UICreateanewdeploymentRadioButton;
            HtmlRadioButton uIEnableAlwaysOnRadioButton1 = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIEnableAlwaysOnRadioButton1;
            HtmlRadioButton uICreateanewCrossOrigiRadioButton = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UICreateanewCrossOrigiRadioButton;
            HtmlDiv uIAzureworkerrolePane = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIAzureworkerrolePane;
            HtmlRadioButton uICreateanewCrossOrigiRadioButton1 = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UICreateanewCrossOrigiRadioButton1;
            HtmlRadioButton uICreateanewdeploymentRadioButton1 = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UICreateanewdeploymentRadioButton1;
            HtmlRadioButton uIEnableAlwaysOnRadioButton11 = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIEnableAlwaysOnRadioButton11;
            HtmlRadioButton uIEnableWebSocketsRadioButton1 = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UIEnableWebSocketsRadioButton1;
            HtmlRadioButton uICreateanewdeploymentRadioButton2 = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UICreateanewdeploymentRadioButton2;
            HtmlInputButton uISubmitAnswersButton = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument.UISubmitAnswersButton;
            BrowserWindow uIBlankPageInternetExpWindow = this.UIBlankPageInternetExpWindow;
            #endregion

            // Type 'Tim Moore' in 'txtName' text box
            uITxtNameEdit.Text = this.TakeExamParams.UITxtNameEditText;

            // Type '{Tab}' in 'txtName' text box
            Keyboard.SendKeys(uITxtNameEdit, this.TakeExamParams.UITxtNameEditSendKeys, ModifierKeys.None);

            // Type 'Moore.Tim@Microsoft.com' in 'txtEmail' text box
            uITxtEmailEdit.Text = this.TakeExamParams.UITxtEmailEditText;

            // Click 'Enable Always On' label
            Mouse.Click(uIEnableAlwaysOnLabel, new Point(113, 9));

            // Move 'Home Page - AzureExam' document
            Mouse.StartDragging(uIHomePageAzureExamDocument, new Point(1914, 162));
            Mouse.StopDragging(uIHomePageAzureExamDocument, -1, 245);

            // Click 'Deployment slots' label
            Mouse.Click(uIDeploymentslotsLabel, new Point(68, 8));

            // Click 'Deployment slots' label
            Mouse.Click(uIDeploymentslotsLabel, new Point(70, 6));

            // Select 'Enable Web Sockets' radio button
            uIEnableWebSocketsRadioButton.Selected = this.TakeExamParams.UIEnableWebSocketsRadioButtonSelected;

            // Click 'API Management' label
            Mouse.Click(uIAPIManagementLabel, new Point(39, 13));

            // Select 'Create a new deployment slot' radio button
            uICreateanewdeploymentRadioButton.Selected = this.TakeExamParams.UICreateanewdeploymentRadioButtonSelected;

            // Select 'Enable Always On' radio button
            uIEnableAlwaysOnRadioButton1.Selected = this.TakeExamParams.UIEnableAlwaysOnRadioButton1Selected;

            // Move 'Home Page - AzureExam' document
            Mouse.StartDragging(uIHomePageAzureExamDocument, new Point(1919, 399));
            Mouse.StopDragging(uIHomePageAzureExamDocument, 0, 205);

            // Select 'Create a new Cross Origin Resource Sharing (CORS)...' radio button
            uICreateanewCrossOrigiRadioButton.Selected = this.TakeExamParams.UICreateanewCrossOrigiRadioButtonSelected;

            // Click 'Azure worker role' pane
            Mouse.Click(uIAzureworkerrolePane, new Point(14, 10));

            // Select 'Create a new Cross Origin Resource Sharing (CORS)...' radio button
            uICreateanewCrossOrigiRadioButton1.Selected = this.TakeExamParams.UICreateanewCrossOrigiRadioButton1Selected;

            // Select 'Create a new deployment slot' radio button
            uICreateanewdeploymentRadioButton1.Selected = this.TakeExamParams.UICreateanewdeploymentRadioButton1Selected;

            // Move 'Home Page - AzureExam' document
            Mouse.StartDragging(uIHomePageAzureExamDocument, new Point(1919, 645));
            Mouse.StopDragging(uIHomePageAzureExamDocument, 0, 146);

            // Select 'Enable Always On' radio button
            uIEnableAlwaysOnRadioButton11.Selected = this.TakeExamParams.UIEnableAlwaysOnRadioButton11Selected;

            // Select 'Enable Web Sockets' radio button
            uIEnableWebSocketsRadioButton1.Selected = this.TakeExamParams.UIEnableWebSocketsRadioButton1Selected;

            // Select 'Create a new deployment slot' radio button
            uICreateanewdeploymentRadioButton2.Selected = this.TakeExamParams.UICreateanewdeploymentRadioButton2Selected;

            // Move 'Home Page - AzureExam' document
            Mouse.StartDragging(uIHomePageAzureExamDocument, new Point(1915, 745));
            Mouse.StopDragging(uIHomePageAzureExamDocument, -10, 51);

            // Click 'Submit Answers' button
            Mouse.Click(uISubmitAnswersButton, new Point(122, 11));

            // Click 'Ok' button in the browser dialog window
            uIBlankPageInternetExpWindow.PerformDialogAction(BrowserDialogAction.Ok);

            // Click 'Ok' button in the browser dialog window
            uIBlankPageInternetExpWindow.PerformDialogAction(BrowserDialogAction.Ok);
        }
        
        /// <summary>
        /// CheckPassedExam - Use 'CheckPassedExamExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckPassedExam()
        {
            #region Variable Declarations
            HtmlDiv uIGreatJobPane = this.UIBlankPageInternetExpWindow.UIHomePageAzureExamDocument1.UIGreatJobPane;
            #endregion

            // Verify that the 'InnerText' property of 'Great Job!' pane equals 'Great Job!'
            Assert.AreEqual(this.CheckPassedExamExpectedValues.UIGreatJobPaneInnerText, uIGreatJobPane.InnerText, "Failed Exam");
        }
        
        #region Properties
        public virtual OpenHomePageParams OpenHomePageParams
        {
            get
            {
                if ((this.mOpenHomePageParams == null))
                {
                    this.mOpenHomePageParams = new OpenHomePageParams();
                }
                return this.mOpenHomePageParams;
            }
        }
        
        public virtual TakeExamParams TakeExamParams
        {
            get
            {
                if ((this.mTakeExamParams == null))
                {
                    this.mTakeExamParams = new TakeExamParams();
                }
                return this.mTakeExamParams;
            }
        }
        
        public virtual CheckPassedExamExpectedValues CheckPassedExamExpectedValues
        {
            get
            {
                if ((this.mCheckPassedExamExpectedValues == null))
                {
                    this.mCheckPassedExamExpectedValues = new CheckPassedExamExpectedValues();
                }
                return this.mCheckPassedExamExpectedValues;
            }
        }
        
        public UIBlankPageInternetExpWindow UIBlankPageInternetExpWindow
        {
            get
            {
                if ((this.mUIBlankPageInternetExpWindow == null))
                {
                    this.mUIBlankPageInternetExpWindow = new UIBlankPageInternetExpWindow();
                }
                return this.mUIBlankPageInternetExpWindow;
            }
        }
        #endregion
        
        #region Fields
        private OpenHomePageParams mOpenHomePageParams;
        
        private TakeExamParams mTakeExamParams;
        
        private CheckPassedExamExpectedValues mCheckPassedExamExpectedValues;
        
        private UIBlankPageInternetExpWindow mUIBlankPageInternetExpWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenHomePage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class OpenHomePageParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:5000/exAm?sf=8d679ae7-e939-474c-a3ff-8501ee636b12'
        /// </summary>
        public string UIBlankPageInternetExpWindowUrl = "http://localhost:5000/exAm?sf=8d679ae7-e939-474c-a3ff-8501ee636b12";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TakeExam'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class TakeExamParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Tim Moore' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditText = "Tim Moore";
        
        /// <summary>
        /// Type '{Tab}' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Moore.Tim@Microsoft.com' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditText = "Moore.Tim@Microsoft.com";
        
        /// <summary>
        /// Select 'Enable Web Sockets' radio button
        /// </summary>
        public bool UIEnableWebSocketsRadioButtonSelected = true;
        
        /// <summary>
        /// Select 'Create a new deployment slot' radio button
        /// </summary>
        public bool UICreateanewdeploymentRadioButtonSelected = true;
        
        /// <summary>
        /// Select 'Enable Always On' radio button
        /// </summary>
        public bool UIEnableAlwaysOnRadioButton1Selected = true;
        
        /// <summary>
        /// Select 'Create a new Cross Origin Resource Sharing (CORS)...' radio button
        /// </summary>
        public bool UICreateanewCrossOrigiRadioButtonSelected = true;
        
        /// <summary>
        /// Select 'Create a new Cross Origin Resource Sharing (CORS)...' radio button
        /// </summary>
        public bool UICreateanewCrossOrigiRadioButton1Selected = true;
        
        /// <summary>
        /// Select 'Create a new deployment slot' radio button
        /// </summary>
        public bool UICreateanewdeploymentRadioButton1Selected = true;
        
        /// <summary>
        /// Select 'Enable Always On' radio button
        /// </summary>
        public bool UIEnableAlwaysOnRadioButton11Selected = true;
        
        /// <summary>
        /// Select 'Enable Web Sockets' radio button
        /// </summary>
        public bool UIEnableWebSocketsRadioButton1Selected = true;
        
        /// <summary>
        /// Select 'Create a new deployment slot' radio button
        /// </summary>
        public bool UICreateanewdeploymentRadioButton2Selected = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckPassedExam'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class CheckPassedExamExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Great Job!' pane equals 'Great Job!'
        /// </summary>
        public string UIGreatJobPaneInnerText = "Great Job!";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBlankPageInternetExpWindow : BrowserWindow
    {
        
        public UIBlankPageInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Blank Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("Home Page - AzureExam");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageAzureExamDocument UIHomePageAzureExamDocument
        {
            get
            {
                if ((this.mUIHomePageAzureExamDocument == null))
                {
                    this.mUIHomePageAzureExamDocument = new UIHomePageAzureExamDocument(this);
                }
                return this.mUIHomePageAzureExamDocument;
            }
        }
        
        public UIHomePageAzureExamDocument1 UIHomePageAzureExamDocument1
        {
            get
            {
                if ((this.mUIHomePageAzureExamDocument1 == null))
                {
                    this.mUIHomePageAzureExamDocument1 = new UIHomePageAzureExamDocument1(this);
                }
                return this.mUIHomePageAzureExamDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageAzureExamDocument mUIHomePageAzureExamDocument;
        
        private UIHomePageAzureExamDocument1 mUIHomePageAzureExamDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageAzureExamDocument : HtmlDocument
    {
        
        public UIHomePageAzureExamDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - AzureExam";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/exAm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5000/exAm?sf=8d679ae7-e939-474c-a3ff-8501ee636b12";
            this.WindowTitles.Add("Home Page - AzureExam");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UITxtNameEdit
        {
            get
            {
                if ((this.mUITxtNameEdit == null))
                {
                    this.mUITxtNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITxtNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "txtName";
                    this.mUITxtNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "txtName";
                    this.mUITxtNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUITxtNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITxtNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITxtNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUITxtNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"txtName\" id=\"txtName\" style=\"width";
                    this.mUITxtNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUITxtNameEdit.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUITxtNameEdit;
            }
        }
        
        public HtmlEdit UITxtEmailEdit
        {
            get
            {
                if ((this.mUITxtEmailEdit == null))
                {
                    this.mUITxtEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITxtEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "txtEmail";
                    this.mUITxtEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "txtEmail";
                    this.mUITxtEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUITxtEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITxtEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITxtEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUITxtEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"txtEmail\" id=\"txtEmail\" style=\"wid";
                    this.mUITxtEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUITxtEmailEdit.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUITxtEmailEdit;
            }
        }
        
        public HtmlRadioButton UIEnableAlwaysOnRadioButton
        {
            get
            {
                if ((this.mUIEnableAlwaysOnRadioButton == null))
                {
                    this.mUIEnableAlwaysOnRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIEnableAlwaysOnRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_36714";
                    this.mUIEnableAlwaysOnRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_36714";
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Enable Always On ";
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_36714\" class=\"rdoAnswer\" id";
                    this.mUIEnableAlwaysOnRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "3";
                    this.mUIEnableAlwaysOnRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIEnableAlwaysOnRadioButton;
            }
        }
        
        public HtmlRadioButton UIDeploymentslotsRadioButton
        {
            get
            {
                if ((this.mUIDeploymentslotsRadioButton == null))
                {
                    this.mUIDeploymentslotsRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIDeploymentslotsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_82161";
                    this.mUIDeploymentslotsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_82161";
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Deployment slots ";
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_82161\" class=\"rdoAnswer\" id";
                    this.mUIDeploymentslotsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "8";
                    this.mUIDeploymentslotsRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIDeploymentslotsRadioButton;
            }
        }
        
        public HtmlRadioButton UIAPIManagementRadioButton
        {
            get
            {
                if ((this.mUIAPIManagementRadioButton == null))
                {
                    this.mUIAPIManagementRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIAPIManagementRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_61536";
                    this.mUIAPIManagementRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_61536";
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " API Management ";
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_61536\" class=\"rdoAnswer\" id";
                    this.mUIAPIManagementRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "13";
                    this.mUIAPIManagementRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIAPIManagementRadioButton;
            }
        }
        
        public HtmlRadioButton UIZoneredundantstorageRadioButton
        {
            get
            {
                if ((this.mUIZoneredundantstorageRadioButton == null))
                {
                    this.mUIZoneredundantstorageRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIZoneredundantstorageRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_54482";
                    this.mUIZoneredundantstorageRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_54482";
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Zone-redundant storage (ZRS) ";
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_54482\" class=\"rdoAnswer\" id";
                    this.mUIZoneredundantstorageRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "15";
                    this.mUIZoneredundantstorageRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIZoneredundantstorageRadioButton;
            }
        }
        
        public HtmlRadioButton UIBlobRadioButton
        {
            get
            {
                if ((this.mUIBlobRadioButton == null))
                {
                    this.mUIBlobRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIBlobRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_11755";
                    this.mUIBlobRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_11755";
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Blob ";
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_11755\" class=\"rdoAnswer\" id";
                    this.mUIBlobRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "22";
                    this.mUIBlobRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIBlobRadioButton;
            }
        }
        
        public HtmlRadioButton UIAzureworkerroleRadioButton
        {
            get
            {
                if ((this.mUIAzureworkerroleRadioButton == null))
                {
                    this.mUIAzureworkerroleRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIAzureworkerroleRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_17895";
                    this.mUIAzureworkerroleRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_17895";
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Azure worker role ";
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_17895\" class=\"rdoAnswer\" id";
                    this.mUIAzureworkerroleRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "26";
                    this.mUIAzureworkerroleRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIAzureworkerroleRadioButton;
            }
        }
        
        public HtmlRadioButton UIAmultifactorauthentiRadioButton
        {
            get
            {
                if ((this.mUIAmultifactorauthentiRadioButton == null))
                {
                    this.mUIAmultifactorauthentiRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIAmultifactorauthentiRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_70314";
                    this.mUIAmultifactorauthentiRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_70314";
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " A multi-factor authentication server ";
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_70314\" class=\"rdoAnswer\" id";
                    this.mUIAmultifactorauthentiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "29";
                    this.mUIAmultifactorauthentiRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIAmultifactorauthentiRadioButton;
            }
        }
        
        public HtmlRadioButton UIApplicationInsightsRadioButton
        {
            get
            {
                if ((this.mUIApplicationInsightsRadioButton == null))
                {
                    this.mUIApplicationInsightsRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIApplicationInsightsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_63809";
                    this.mUIApplicationInsightsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_63809";
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Application Insights ";
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_63809\" class=\"rdoAnswer\" id";
                    this.mUIApplicationInsightsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "31";
                    this.mUIApplicationInsightsRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIApplicationInsightsRadioButton;
            }
        }
        
        public HtmlRadioButton UIFaultDomainsRadioButton
        {
            get
            {
                if ((this.mUIFaultDomainsRadioButton == null))
                {
                    this.mUIFaultDomainsRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIFaultDomainsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_16304";
                    this.mUIFaultDomainsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_16304";
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Fault Domains ";
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_16304\" class=\"rdoAnswer\" id";
                    this.mUIFaultDomainsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "36";
                    this.mUIFaultDomainsRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIFaultDomainsRadioButton;
            }
        }
        
        public HtmlRadioButton UISwaggerRadioButton
        {
            get
            {
                if ((this.mUISwaggerRadioButton == null))
                {
                    this.mUISwaggerRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUISwaggerRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_85392";
                    this.mUISwaggerRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_85392";
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Swagger ";
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_85392\" class=\"rdoAnswer\" id";
                    this.mUISwaggerRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "41";
                    this.mUISwaggerRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUISwaggerRadioButton;
            }
        }
        
        public HtmlInputButton UISubmitAnswersButton
        {
            get
            {
                if ((this.mUISubmitAnswersButton == null))
                {
                    this.mUISubmitAnswersButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISubmitAnswersButton.SearchProperties[HtmlButton.PropertyNames.Id] = "txtSubmit";
                    this.mUISubmitAnswersButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISubmitAnswersButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Submit Answers";
                    this.mUISubmitAnswersButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISubmitAnswersButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISubmitAnswersButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUISubmitAnswersButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"txtSubmit\" style=\"margin: 30px; widt";
                    this.mUISubmitAnswersButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "43";
                    this.mUISubmitAnswersButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUISubmitAnswersButton;
            }
        }
        
        public HtmlLabel UIEnableAlwaysOnLabel
        {
            get
            {
                if ((this.mUIEnableAlwaysOnLabel == null))
                {
                    this.mUIEnableAlwaysOnLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mUIEnableAlwaysOnLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mUIEnableAlwaysOnLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mUIEnableAlwaysOnLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "answer_1001";
                    this.mUIEnableAlwaysOnLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = " Enable Always On ";
                    this.mUIEnableAlwaysOnLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = "lblAnswer";
                    this.mUIEnableAlwaysOnLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "class=\"lblAnswer\" for=\"answer_1001\"";
                    this.mUIEnableAlwaysOnLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "1";
                    this.mUIEnableAlwaysOnLabel.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIEnableAlwaysOnLabel;
            }
        }
        
        public HtmlLabel UIDeploymentslotsLabel
        {
            get
            {
                if ((this.mUIDeploymentslotsLabel == null))
                {
                    this.mUIDeploymentslotsLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mUIDeploymentslotsLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mUIDeploymentslotsLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mUIDeploymentslotsLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "answer_1002";
                    this.mUIDeploymentslotsLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = " Deployment slots ";
                    this.mUIDeploymentslotsLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = "lblAnswer";
                    this.mUIDeploymentslotsLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "class=\"lblAnswer\" for=\"answer_1002\"";
                    this.mUIDeploymentslotsLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "6";
                    this.mUIDeploymentslotsLabel.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIDeploymentslotsLabel;
            }
        }
        
        public HtmlRadioButton UIEnableWebSocketsRadioButton
        {
            get
            {
                if ((this.mUIEnableWebSocketsRadioButton == null))
                {
                    this.mUIEnableWebSocketsRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIEnableWebSocketsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1002";
                    this.mUIEnableWebSocketsRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1002";
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Enable Web Sockets ";
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1002\" class=\"rdoAnswer\" id=";
                    this.mUIEnableWebSocketsRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "8";
                    this.mUIEnableWebSocketsRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIEnableWebSocketsRadioButton;
            }
        }
        
        public HtmlLabel UIAPIManagementLabel
        {
            get
            {
                if ((this.mUIAPIManagementLabel == null))
                {
                    this.mUIAPIManagementLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mUIAPIManagementLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mUIAPIManagementLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mUIAPIManagementLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "answer_1003";
                    this.mUIAPIManagementLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = " API Management ";
                    this.mUIAPIManagementLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = "lblAnswer";
                    this.mUIAPIManagementLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "class=\"lblAnswer\" for=\"answer_1003\"";
                    this.mUIAPIManagementLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "11";
                    this.mUIAPIManagementLabel.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIAPIManagementLabel;
            }
        }
        
        public HtmlRadioButton UICreateanewdeploymentRadioButton
        {
            get
            {
                if ((this.mUICreateanewdeploymentRadioButton == null))
                {
                    this.mUICreateanewdeploymentRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUICreateanewdeploymentRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1003";
                    this.mUICreateanewdeploymentRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1003";
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Create a new deployment slot ";
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1003\" class=\"rdoAnswer\" id=";
                    this.mUICreateanewdeploymentRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "13";
                    this.mUICreateanewdeploymentRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUICreateanewdeploymentRadioButton;
            }
        }
        
        public HtmlRadioButton UIEnableAlwaysOnRadioButton1
        {
            get
            {
                if ((this.mUIEnableAlwaysOnRadioButton1 == null))
                {
                    this.mUIEnableAlwaysOnRadioButton1 = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIEnableAlwaysOnRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1001";
                    this.mUIEnableAlwaysOnRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1001";
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Enable Always On ";
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1001\" class=\"rdoAnswer\" id=";
                    this.mUIEnableAlwaysOnRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "15";
                    this.mUIEnableAlwaysOnRadioButton1.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIEnableAlwaysOnRadioButton1;
            }
        }
        
        public HtmlRadioButton UICreateanewCrossOrigiRadioButton
        {
            get
            {
                if ((this.mUICreateanewCrossOrigiRadioButton == null))
                {
                    this.mUICreateanewCrossOrigiRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUICreateanewCrossOrigiRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1004";
                    this.mUICreateanewCrossOrigiRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1004";
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Create a new Cross Origin Resource Sharing (CORS) allowed origin ";
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1004\" class=\"rdoAnswer\" id=";
                    this.mUICreateanewCrossOrigiRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "22";
                    this.mUICreateanewCrossOrigiRadioButton.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUICreateanewCrossOrigiRadioButton;
            }
        }
        
        public HtmlDiv UIAzureworkerrolePane
        {
            get
            {
                if ((this.mUIAzureworkerrolePane == null))
                {
                    this.mUIAzureworkerrolePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAzureworkerrolePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAzureworkerrolePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAzureworkerrolePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Azure worker role  ";
                    this.mUIAzureworkerrolePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAzureworkerrolePane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIAzureworkerrolePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"margin: 5px 10px;\"";
                    this.mUIAzureworkerrolePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "44";
                    this.mUIAzureworkerrolePane.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIAzureworkerrolePane;
            }
        }
        
        public HtmlRadioButton UICreateanewCrossOrigiRadioButton1
        {
            get
            {
                if ((this.mUICreateanewCrossOrigiRadioButton1 == null))
                {
                    this.mUICreateanewCrossOrigiRadioButton1 = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUICreateanewCrossOrigiRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1004";
                    this.mUICreateanewCrossOrigiRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1004";
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Create a new Cross Origin Resource Sharing (CORS) allowed origin ";
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1004\" class=\"rdoAnswer\" id=";
                    this.mUICreateanewCrossOrigiRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "26";
                    this.mUICreateanewCrossOrigiRadioButton1.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUICreateanewCrossOrigiRadioButton1;
            }
        }
        
        public HtmlRadioButton UICreateanewdeploymentRadioButton1
        {
            get
            {
                if ((this.mUICreateanewdeploymentRadioButton1 == null))
                {
                    this.mUICreateanewdeploymentRadioButton1 = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUICreateanewdeploymentRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1003";
                    this.mUICreateanewdeploymentRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1003";
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Create a new deployment slot ";
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1003\" class=\"rdoAnswer\" id=";
                    this.mUICreateanewdeploymentRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "29";
                    this.mUICreateanewdeploymentRadioButton1.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUICreateanewdeploymentRadioButton1;
            }
        }
        
        public HtmlRadioButton UIEnableAlwaysOnRadioButton11
        {
            get
            {
                if ((this.mUIEnableAlwaysOnRadioButton11 == null))
                {
                    this.mUIEnableAlwaysOnRadioButton11 = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIEnableAlwaysOnRadioButton11.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1001";
                    this.mUIEnableAlwaysOnRadioButton11.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1001";
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Enable Always On ";
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1001\" class=\"rdoAnswer\" id=";
                    this.mUIEnableAlwaysOnRadioButton11.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "31";
                    this.mUIEnableAlwaysOnRadioButton11.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIEnableAlwaysOnRadioButton11;
            }
        }
        
        public HtmlRadioButton UIEnableWebSocketsRadioButton1
        {
            get
            {
                if ((this.mUIEnableWebSocketsRadioButton1 == null))
                {
                    this.mUIEnableWebSocketsRadioButton1 = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIEnableWebSocketsRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1002";
                    this.mUIEnableWebSocketsRadioButton1.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1002";
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Enable Web Sockets ";
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1002\" class=\"rdoAnswer\" id=";
                    this.mUIEnableWebSocketsRadioButton1.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "36";
                    this.mUIEnableWebSocketsRadioButton1.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIEnableWebSocketsRadioButton1;
            }
        }
        
        public HtmlRadioButton UICreateanewdeploymentRadioButton2
        {
            get
            {
                if ((this.mUICreateanewdeploymentRadioButton2 == null))
                {
                    this.mUICreateanewdeploymentRadioButton2 = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUICreateanewdeploymentRadioButton2.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "answer_1003";
                    this.mUICreateanewdeploymentRadioButton2.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "answer_1003";
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "on";
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = " Create a new deployment slot ";
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "10";
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "rdoAnswer";
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"answer_1003\" class=\"rdoAnswer\" id=";
                    this.mUICreateanewdeploymentRadioButton2.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "41";
                    this.mUICreateanewdeploymentRadioButton2.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUICreateanewdeploymentRadioButton2;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUITxtNameEdit;
        
        private HtmlEdit mUITxtEmailEdit;
        
        private HtmlRadioButton mUIEnableAlwaysOnRadioButton;
        
        private HtmlRadioButton mUIDeploymentslotsRadioButton;
        
        private HtmlRadioButton mUIAPIManagementRadioButton;
        
        private HtmlRadioButton mUIZoneredundantstorageRadioButton;
        
        private HtmlRadioButton mUIBlobRadioButton;
        
        private HtmlRadioButton mUIAzureworkerroleRadioButton;
        
        private HtmlRadioButton mUIAmultifactorauthentiRadioButton;
        
        private HtmlRadioButton mUIApplicationInsightsRadioButton;
        
        private HtmlRadioButton mUIFaultDomainsRadioButton;
        
        private HtmlRadioButton mUISwaggerRadioButton;
        
        private HtmlInputButton mUISubmitAnswersButton;
        
        private HtmlLabel mUIEnableAlwaysOnLabel;
        
        private HtmlLabel mUIDeploymentslotsLabel;
        
        private HtmlRadioButton mUIEnableWebSocketsRadioButton;
        
        private HtmlLabel mUIAPIManagementLabel;
        
        private HtmlRadioButton mUICreateanewdeploymentRadioButton;
        
        private HtmlRadioButton mUIEnableAlwaysOnRadioButton1;
        
        private HtmlRadioButton mUICreateanewCrossOrigiRadioButton;
        
        private HtmlDiv mUIAzureworkerrolePane;
        
        private HtmlRadioButton mUICreateanewCrossOrigiRadioButton1;
        
        private HtmlRadioButton mUICreateanewdeploymentRadioButton1;
        
        private HtmlRadioButton mUIEnableAlwaysOnRadioButton11;
        
        private HtmlRadioButton mUIEnableWebSocketsRadioButton1;
        
        private HtmlRadioButton mUICreateanewdeploymentRadioButton2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageAzureExamDocument1 : HtmlDocument
    {
        
        public UIHomePageAzureExamDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - AzureExam";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Exam";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5000/Exam";
            this.WindowTitles.Add("Home Page - AzureExam");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIGreatJobPane
        {
            get
            {
                if ((this.mUIGreatJobPane == null))
                {
                    this.mUIGreatJobPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIGreatJobPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "divPassMessage";
                    this.mUIGreatJobPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIGreatJobPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Great Job!";
                    this.mUIGreatJobPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIGreatJobPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIGreatJobPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"divPassMessage\" style=\"left: 41%; top: 20px; color: green; font-size: 5.3em; " +
                        "position: absolute; z-index: 100;\"";
                    this.mUIGreatJobPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIGreatJobPane.WindowTitles.Add("Home Page - AzureExam");
                    #endregion
                }
                return this.mUIGreatJobPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIGreatJobPane;
        #endregion
    }
}
