using System;

namespace LIM.Certificates.Models
{
    //Report generated by SSRS
    public class Certificate
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }

        public byte[] FileContents { get; set; }
        public string FileName { get; set; }

    }
}

